# Site settings
title: Hybrid Mobile Development Tutorial
email: naveen.pnd@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/MobileDev101"
url: "http://nav13n.github.io" # the base hostname & protocol for your site
twitter_username: naveenpnd
github_username:  nav13n

# Build settings
markdown: kramdown
highlighter: pygments
